<?php
/**
 * Plugin Name:     StoreEngine Square
 * Plugin URI:      https://storeengine.pro
 * Description:     Square Payment Gateway for StoreEngine — accept cards via Square Web Payments SDK.
 * Version:         1.0.0
 * Author:          Kodezen
 * Author URI:      https://kodezen.com
 * License:         GPL-3.0+
 * License URI:     http://www.gnu.org/licenses/gpl-3.0.txt
 * Text Domain:     storeengine-square
 * Domain Path:     /languages/
 *
 * Requires PHP:          7.4
 * Requires at least:     6.5
 * Requires Plugins:      storeengine
 *
 * @package StoreEngineSquare
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ── StoreEngine dependency guard ──────────────────────────────────────────────
add_action( 'plugins_loaded', static function () {

	if ( ! function_exists( 'storeengine' ) ) {
		add_action( 'admin_notices', static function () {
			?>
			<div class="notice notice-error">
				<p>
					<?php
					echo wp_kses_post(
						sprintf(
						/* translators: %s: StoreEngine plugin link */
							__( '<strong>StoreEngine Square</strong> requires %s to be installed and active.', 'storeengine-square' ),
							'<a href="https://storeengine.pro" target="_blank">StoreEngine</a>'
						)
					);
					?>
				</p>
			</div>
			<?php
		} );
		return;
	}

	StoreEngineSquarePayments::get_instance()->run();

}, 5 );

// ── Plugin bootstrap ──────────────────────────────────────────────────────────

final class StoreEngineSquarePayments {

	private static ?StoreEngineSquarePayments $instance = null;

	public static function get_instance(): StoreEngineSquarePayments {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	private function __construct() {}

	public function run(): void {
		$this->define_constants();

		if ( ! $this->load_composer() ) {
			return; // Admin notice already scheduled inside load_composer().
		}

		add_action( 'storeengine_init', [ $this, 'init' ] );
		add_action( 'init', [ $this, 'load_textdomain' ] );
	}

	// ── Constants ─────────────────────────────────────────────────────────────

	private function define_constants(): void {
		define( 'SE_SQUARE_VERSION', '1.0.0' );
		define( 'SE_SQUARE_FILE',    __FILE__ );
		define( 'SE_SQUARE_DIR',     plugin_dir_path( __FILE__ ) );
		define( 'SE_SQUARE_URL',     plugin_dir_url( __FILE__ ) );
		define( 'SE_SQUARE_SRC_DIR', plugin_dir_path( __FILE__ ) . 'src/' );
	}

	// ── Composer autoloader ───────────────────────────────────────────────────

	/**
	 * Load vendor/autoload.php generated by `composer install --no-dev -o`.
	 *
	 * This registers:
	 *   - Square\* (the official square/square SDK)
	 *   - StoreEngineSquare\* (this plugin's own src/ classes via PSR-4 in composer.json)
	 *
	 * @return bool  False if vendor/autoload.php is missing (admin notice shown).
	 */
	private function load_composer(): bool {
		$autoload = SE_SQUARE_DIR . 'vendor/autoload.php';

		if ( ! file_exists( $autoload ) ) {
			add_action( 'admin_notices', static function () {
				?>
				<div class="notice notice-error">
					<p>
						<?php
						echo wp_kses_post(
							sprintf(
							/* translators: %s: shell command */
								__( '<strong>StoreEngine Square:</strong> Composer dependencies are missing. Run %s inside the plugin directory and re-activate.', 'storeengine-square' ),
								'<code>composer install --no-dev -o</code>'
							)
						);
						?>
					</p>
				</div>
				<?php
			} );

			return false;
		}

		require_once $autoload;

		return true;
	}

	// ── Initialization ────────────────────────────────────────────────────────

	public function init(): void {
		// Register GatewaySquare with StoreEngine's payment gateway list.
		add_filter( 'storeengine/payment_gateways', [ $this, 'register_gateway' ] );

		// When StoreEngine boots the gateway, wire up supporting services.
		add_action( 'storeengine/gateway/square/init', static function ( $gateway ) {
			StoreEngineSquare\Hooks::init( $gateway );
			StoreEngineSquare\Ajax::init();
			StoreEngineSquare\Api::init();
			StoreEngineSquare\Assets::init( $gateway );
		} );
	}

	public function register_gateway( array $gateways ): array {
		$gateways[] = StoreEngineSquare\GatewaySquare::class;

		return $gateways;
	}

	public function load_textdomain(): void {
		load_plugin_textdomain(
			'storeengine-square',
			false,
			dirname( plugin_basename( SE_SQUARE_FILE ) ) . '/languages/'
		);
	}
}
